### ISSUE TITLE
Performance regression materializing `Selection`

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/libsonata#364]
Two people independently contacted me about a large performance regression while materializing Selections.
They had to roll back to 0.1.24 to be able to complete selections.
It seems that operations that completed nearly instantly (if the data was cached) are now taking much longer.
I will try and make a reproducer.

**Comment by mgeplf** [comment]
git bisect is point me at:
```
git bisect start
# status: waiting for both good and bad commits
# bad: [a7d1453fadce88201d009ea3c843f562491238bf] Refactor edge_index::resolve. (#314)
git bisect bad a7d1453fadce88201d009ea3c843f562491238bf
# status: waiting for good commit(s), bad commit known
# good: [e49d49c2b844d6e8834e723ae376eae92f74c5dd] update changelog
git bisect good e49d49c2b844d6e8834e723ae376eae92f74c5dd
# good: [e88979a66bdf17304633e39b724085d3020c6be8] Simplify HighFive usage. (#304)
git bisect good e88979a66bdf17304633e39b724085d3020c6be8
# good: [5932272aeedcb89491242d3c04995bccd4ef5b85] Update HighFive to v2.8.0. (#318)
git bisect good 5932272aeedcb89491242d3c04995bccd4ef5b85
# good: [f6abd8bab6cd19da3b9fed2c73b31e73b1fe857d] update to require using cmake 3.16 (#321)
git bisect good f6abd8bab6cd19da3b9fed2c73b31e73b1fe857d
# bad: [c2e8b5eefc9b70e0245fb422d9ad6a01b70245fa] Refactor `_readSelection`. (#315)
git bisect bad c2e8b5eefc9b70e0245fb422d9ad6a01b70245fa
# good: [f65a0aec9197f6e74c8d75e8f78641326127dfce] Prevent pytest from picking up pybind11 tests. (#320)
git bisect good f65a0aec9197f6e74c8d75e8f78641326127dfce
# first bad commit: [c2e8b5eefc9b70e0245fb422d9ad6a01b70245fa] Refactor `_readSelection`. (#315)
```

**Comment by 1uc** [comment]
The likely issue is the following loop in HighFive:
```
        for (const auto& sel: selects) {
            if (sel.op == Op::None) {
                H5Sselect_none(space.getId());
            } else {
                auto error_code =
                    H5Sselect_hyperslab(space.getId(),
                                        convert(sel.op),
                                        sel.offset.empty() ? nullptr : sel.offset.data(),
                                        sel.stride.empty() ? nullptr : sel.stride.data(),
                                        sel.count.empty() ? nullptr : sel.count.data(),
                                        sel.block.empty() ? nullptr : sel.block.data());

                if (error_code < 0) {
                    HDF5ErrMapper::ToException<DataSpaceException>("Unable to select hyperslab");
                }
            }
        }
```
which has runtime that's quadratic in the number of selections. This can be optimized by a divide and conquer algorithm built on top of `H5Scombine_select`.

**Comment by mgeplf** [comment]
Nice find @1uc!
Thanks for looking into it.

**Comment by mgeplf** [comment]
@1uc has created a change in HighFive that should fix this:
https://github.com/BlueBrain/HighFive/pull/1031

I think it's worth waiting for that to make it into HighFive, and then released.
Then we can upgrade libsonata, and release it.

**Comment by mgeplf** [comment]
I've had a report that it's still slower:
```
libsonata 0.1.24
Executed sample_nodes in process 179790 in 2.886 seconds
13.50user 9.57system 0:05.85elapsed 394%CPU (0avgtext+0avgdata 238960maxresident)k
0inputs+0outputs (0major+125862minor)pagefaults 0swaps

libsonata 0.1.28:
Executed sample_nodes in process 180903 in 22.635 seconds
32.54user 10.25system 0:25.54elapsed 167%CPU (0avgtext+0avgdata 493064maxresident)k
0inputs+0outputs (0major+159994minor)pagefaults 0swaps
```
However, I'm not sure we need to put effort in on this at the moment; if so, I'll reopen the ticket.

**Comment by 1uc** [comment]
Remember that `libsonata` itself didn't fix anything. The fix is in HighFive; and HighFive requires at HDF5 1.10.x to implements the fix. Therefore, if anything is using an older version those two dependencies will not see that anything was fixed.

**Comment by mgeplf** [comment]
Good point; it's the wheel version from PyPi, and so it should be included.
In addition, it's (paraphrased) `7.4 times slower than 0.1.24, while 0.1.27 was much slower than that`

**Comment by 1uc** [comment]
Okay, so there's more to be fixed.

**Comment by 1uc** [comment]
The regression is not related to anything I/O? Only building the `libsonata.Selection`? Can `pop.size` be replaced with `pop_size = 71_000_000` to get an equivalent benchmark?

**Comment by mgeplf** [comment]
I'll get back to you, I just wanted to write this down.

**Comment by mgeplf** [comment]
Ok, here are the flame graphs:
![0 1 24](https://github.com/user-attachments/assets/59d464cb-5e49-45df-a7ac-e1dad40b6fd8)
![latest](https://github.com/user-attachments/assets/30ae34f0-ba01-418f-bbfb-6b0cc9a3db5c)

**Comment by 1uc** [comment]
Using a 71M `nodes.h5` we measure how long it takes to do:
```
pop.get_attribute('x', sel)
```

The selection is the union of `n` index ranges, each of length `m`, each starting at a random offset. To mimic files of different sizes the index ranges where restricted to the first `N` GIDs. We vary `n` and `N` for `m = 1, 10, 100, 1000`.

We measure several versions of libsonata:
* `0.1.25-dirty` refers to `0.1.24` with an updated version of `pybind11`.
* `0.1.29` refers to `master`.
* `0.1.29-bR_{k}` refers to `master` with bulk reading, allowing aggregation of at most `k` pages.

In order to see more easily which measurement belong to which variation of libsonata, we offset them horizontally; and treat `block_size` as a categorical variable. We measure on an HDD and an SSD.

We created a PR for `bR_1` in #374.

![runtime_hdd](https://github.com/user-attachments/assets/e835e724-fbfe-471b-8a14-ed67478624b5)
![runtime_ssd](https://github.com/user-attachments/assets/dbdf514e-b152-46d5-8f3f-cdc397d2cbad)
![speedup_hdd](https://github.com/user-attachments/assets/4ac2617b-ba78-4210-bbcd-d267f48cb298)
![speedup_ssd](https://github.com/user-attachments/assets/67040c83-b7ec-4564-8a28-4c07eab9251a)

**Comment by GianlucaFicarelli** [comment]
Thanks @1uc , amazing improvement. I tried the new wheels on a bb5 allocation for the cells service use case (sampling 1% from 71M nodes) and I'm getting even better results than 0.1.24.
With 4 repetitions I got these times (in seconds):
```
0.1.24 -> 3.111, 2.560, 2.813, 2.735
PR -> 2.493, 2.252, 1.990, 1.800
```
